// app/layout.tsx

import type { Metadata } from "next"
import localFont from "next/font/local"
import "./globals.css"
import Header from "./components/Header"  // ← 헤더 컴포넌트 import

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
})
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 전역 네비게이션 헤더 */}
        <Header />

        {/* 각 페이지 내용 */}
        {children}
      </body>
    </html>
  )
}
